<?php

/*
 * Feste Dialog-IDs (siehe App\Support\DialogId). Nach einer Umbenennung eines Dialogs den neuen
 * Namen mit der ALTEN ID eintragen; neue Dialoge ergänzt `php artisan dialogs:sync`.
 */

return [
    'activate-workflow-step' => 'D-LGVL',
    'anzeigefilter' => 'D-A2LP',
    'business-unit-manager' => 'D-HW4Q',
    'calendar-entry' => 'D-77PW',
    'checklisten-auswaehlen' => 'D-0681',
    'company-manager' => 'D-K137',
    'confirm-user-deletion' => 'D-TQUR',
    'critical-project-details' => 'D-E2OZ',
    'critical-project-organizations' => 'D-VIQW',
    'critical-project-rules' => 'D-G032',
    'department-manager' => 'D-S8MV',
    'favorites' => 'D-JG1H',
    'format-picker' => 'D-X3LK',
    'function-group-availability' => 'D-TXEI',
    'help-article-preview' => 'D-I52C',
    'help-image-lightbox' => 'D-EGMN',
    'help-panel' => 'D-93JW',
    'illustration-orders' => 'D-ZBSX',
    'jobload-jobs' => 'D-OOKJ',
    'jobload-week-detail' => 'D-U7GO',
    'kacheln-verwalten' => 'D-9TT8',
    'legacy-role-manager' => 'D-R37O',
    'morph' => 'D-4BH2',
    'multichange' => 'D-EWKG',
    'papierformate-katalog' => 'D-2BOP',
    'person-overlay' => 'D-GQ8Q',
    'person-vacation-days' => 'D-8766',
    'person-weekly-hours' => 'D-IW2D',
    'personen-zugriffsmatrix' => 'D-8HIV',
    'planning-transfer' => 'D-00FY',
    'produkte-verknuepfen' => 'D-3CO2',
    'project-connection-add' => 'D-2N2T',
    'project-copy' => 'D-GTV9',
    'project-create' => 'D-NRG3',
    'project-directory-content' => 'D-FI2E',
    'project-directory-create' => 'D-JVP5',
    'project-error-check' => 'D-H98J',
    'project-gantt' => 'D-WEQ7',
    'project-gantt-people' => 'D-XONP',
    'project-overlay' => 'D-MFQU',
    'project-people' => 'D-XNXQ',
    'project-request' => 'D-2VX3',
    'project-schedule' => 'D-AO37',
    'project-template-info' => 'D-YBGB',
    'project-time-tracking' => 'D-78FH',
    'projekt-checklisten' => 'D-R7YD',
    'projektfilter' => 'D-E4DM',
    'projektgruppen-panel' => 'D-TEIR',
    'projektgruppen-panel-uebersicht' => 'D-2EIH',
    'projektplanung-organisationen' => 'D-81D2',
    'projektplanung-personen' => 'D-7BIG',
    'recent-projects' => 'D-O8AB',
    'stamm-id-chain' => 'D-UGZI',
    'verbund-panel' => 'D-E4DF',
    'workflow-step-people' => 'D-QLL4',
];
